### ISSUE TITLE
Resume crashes on Manjaro

### ISSUE THREAD

**Issue by petr-nehez** [EHfive/pulseaudio-modules-bt#10]
I installed this repo on Manjaro via https://aur.archlinux.org/packages/pulseaudio-modules-bt-git/ but I've found out that resuming from suspend basically dies. As soon as the laptop is woken up it is restarted - the title might be misleading but I didn't know how to describe the problem in few words.

There is nothing in the journal and I've been trying 4.18 and also 4.14. 
I had to uninstall it and since then I can resume my laptop again.

**Comment by EHfive** [comment]
Can u confirm this when using `pulseaudio-bluetooth` ?
Please post your /etc/pulse/daemon.conf. (via a pastebin service)

**Comment by petr-nehez** [comment]
With `pulseaudio-bluetooth` I have no such problem.
You can check my `/etc/pulse/daemon.conf` at https://pastebin.com/X7Xhejq3 but I wouldn't say there is anything suspicious.

**Comment by EHfive** [comment]
Manjaro is my daily use OS, but I can't confirm this isuue anyway.
(using `systemctl suspend` command)
Ideally, this issue should never happen.

**Comment by petr-nehez** [comment]
Yes, ideally.
But on my laptop suspend does not work anymore.

As you can see here https://pastebin.com/JrVcA0Zv, there is no error at 10:37:41, it just rebooted.
The only package I had to uninstall was `pulseaudio-modules-bt-git`.

Any idea?

**Comment by petr-nehez** [comment]
I double-checked `pacman.log` and for sure no other package was installed or uninstalled.

**Comment by EHfive** [comment]
Maybe 
https://ubuntuforums.org/showthread.php?t=1556934&p=10190636#post10190636
https://forum.manjaro.org/search?q=acpi_sleep%3Dnonvs
helps u.

**Comment by petr-nehez** [comment]
After updating my Manjaro system I do not face this issue anymore so I guess it had to be an issue with these modules and previous kernel version.
