### ISSUE TITLE
Is AptX Low Latency supported?

### ISSUE THREAD

**Issue by katsar0v** [EHfive/pulseaudio-modules-bt#100]
A lot of devices do not support normal aptX or aptX HD, they support aptX LL instead or FastStream. Are these planned, is it possible to have them includes?

**Comment by EHfive** [comment]
Not planned.

**Comment by ValdikSS** [comment]
@EHfive, actually aptX Low Latency is a subset of aptX, it's not a separate codec but just a special configuration with very low buffer value. It could should be trivial to implement.
Contact me if you need more details, I have a traffic dump somewhere.

**Comment by katsar0v** [comment]
@ValdikSS Thank you a lot for your support. @EHfive aptX LL is actually quite a big percentage of the products using aptX so it could be a big feature. Thanks!

**Comment by OkropNick** [comment]
If @ValdikSS is right, it would be very nice feature for activities like watching concerts or games playing.

**Comment by pali** [comment]
Btw, I have already pulseaudio patches for aptX-LL support based on my pull request:
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/227
I will publish these aptX-LL patches in new pull request after above pull request (on which they are based) is merged.

**Comment by nohajc** [comment]
> I will publish these aptX-LL patches in new pull request after above pull request (on which they are based) is merged.

It would be great if you could publish those changes. I already use pulseaudio built from your pull request to set different SBC profiles (another super-useful feature!) and I'd like to try aptX Low Latency too.
