### ISSUE TITLE
PPA Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by snevas** [EHfive/pulseaudio-modules-bt#108]
Could the PPA include the packages for the latest released LTS release "Focal Fossa"?

**Comment by lucasfijen** [comment]
See the following comment: [#85 (comment](https://github.com/EHfive/pulseaudio-modules-bt/issues/85#issuecomment-618870211)

**Comment by berglh** [comment]
I am working on a PPA for `eoan` and `focal`. When I have the packages published I will need some people to test, then we can add the PPA to the instructions for `eoan` and `focal`.

**Comment by snevas** [comment]
I am at your disposal to test when you are ready.

**Comment by berglh** [comment]
@snevas I have published `focal` and `eaon` on my personal PPA here: https://launchpad.net/~berglh/+archive/ubuntu/pulseaudio-a2dp

Please do the purging and removal of existing packages first on this comment: https://github.com/EHfive/pulseaudio-modules-bt/issues/85#issuecomment-592915350

Then try to add the PPA using the instructions on the PPA page then:
```
sudo apt update
sudo apt install pulseaudio-modules-bt libldac
```
Then reboot, I think.

**Comment by Moosieboy** [comment]
> @snevas I have published `focal` and `eaon` on my personal PPA here: https://launchpad.net/~berglh/+archive/ubuntu/pulseaudio-a2dp
> 
> Please do the purging and removal of existing packages first on this comment: [#85 (comment)](https://github.com/EHfive/pulseaudio-modules-bt/issues/85#issuecomment-592915350)
> 
> Then try to add the PPA using the instructions on the PPA page then:
> 
> ```
> sudo apt update
> sudo apt install pulseaudio-modules-bt libldac
> ```
> 
> Then reboot, I think.
> 
> Please report back on issue #85

Works great. Many thanks for packaging!

**Comment by teranex** [comment]
Thank you @berglh for packaging!
