### ISSUE TITLE
Missing info of libraries that need to be installed

### ISSUE THREAD

**Issue by GiantEnemyCrab** [EHfive/pulseaudio-modules-bt#109]
From Pop!_OS 20.04 (which should be close to Ubuntu 20.04) 
```
~/Documents/pulseaudio-modules-bt/pa/src/pulsecore/module.h:24:10: fatal error: ltdl.h: No such file or directory
   24 | #include <ltdl.h>
```

The fix is
```
apt install libltdl-dev
```

Maybe this should be checked during cmake.

Other libraries that needed to be installed:
```
libbluetooth-dev
```

**Comment by EHfive** [comment]
libltdl is provided by https://www.gnu.org/software/libtool https://github.com/EHfive/pulseaudio-modules-bt#general-installation
