### ISSUE TITLE
New stable package for Arch Linux

### ISSUE THREAD

**Issue by Hayao0819** [EHfive/pulseaudio-modules-bt#116]
I have created a stable version of PKGBUILD in the AUR that gets the sources from the release instead of git.
https://aur.archlinux.org/packages/pulseaudio-modules-bt
Could you please add a link for this package to the Wiki?

**Comment by EHfive** [comment]
Added, https://github.com/EHfive/pulseaudio-modules-bt/wiki/Packages/b41427da82b14b4a12876fc65f431bcd1b821bef
