### ISSUE TITLE
[BUG] HSP/HFP works on my desktop PC, but not on my Laptop (same Headphones)

### ISSUE THREAD

**Issue by ashleysommer** [EHfive/pulseaudio-modules-bt#123]
**Describe the bug**
As described in the title.. Both my laptop and my desktop PC are on Ubuntu 20.04 and both using the same module from the PPA here: https://launchpad.net/~berglh/+archive/ubuntu/pulseaudio-a2dp
AptX and AptX-HD streaming to my headphones works great on both computers.
When I'm on my Desktop PC, I can switch into HSP/HFP mode which allows me to use my microphone, for skype calls etc.
On my Laptop, when I switch to HSP/HFP mode, it causes all of the playing sounds on my computer to freeze (youtube videos act like they're buffering, spotify halts), and no sound is heard, microphone input doesn't work. Switching back to AptX immediately resumes all audio.

**To Reproduce**
Switching from APT-X to HSP/HFP using pavucontrol.
I've also tried switching using `pactl set-card-profile ... headset_head_unit`, and I get the same result.

**Expected behavior**
I'd expect both the desktop and the laptop to work the same. I want to be able to enter HSP/HFP mode on my laptop.

**Environment (please complete the following information):**
 - Distribution Ubuntu 20.04
 - Pulseaudio Version 13.99.1
 - Bluez 5.53-0ubuntu3
 - Version 1.3~r26478861
 - Installing via https://launchpad.net/~berglh/+archive/ubuntu/pulseaudio-a2dp

**Pulseaudio logs:**
https://gist.github.com/ashleysommer/8c66761a1a23d0887d7c24e85a421f2c

**`avinfo` of device:**
`no avinfo on ubuntu`

**Additional context**
Bluetooth chipset in the laptop is `Intel Bluetooth device 22560 [8087:0026]`

**Comment by EHfive** [comment]
Close in favor #121 , it's seems a bluez/kernel issue.
