### ISSUE TITLE
[BUG] No package 'sbc' found

### ISSUE THREAD

**Issue by sergsagan** [EHfive/pulseaudio-modules-bt#127]
I installed all the dependencies but could not install one
Executing the command cmake:

➜ **build git:(master) ✗ cmake ..**
-- Checking for module 'sbc'
-- **No package 'sbc' found**
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
A required package was not found
Call Stack (most recent call first):
/usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
CMakeLists.txt:45 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/sagan/pulseaudio-modules-bt/build/CMakeFiles/CMakeOutput.log".

what is this module sbc and how to install it?
help solve the problem

Ubuntu 20.04
pulseaudio 13.99.1
bluez - 5.53-0ubuntu3

**Comment by EHfive** [comment]
Devel package is required.
https://packages.ubuntu.com/focal/libsbc-dev
