### ISSUE TITLE
Disable some profiles

### ISSUE THREAD

**Issue by Enelar** [EHfive/pulseaudio-modules-bt#13]
My android phone starting play as `SBC`, then immediately switch to the `aptX HD`. I've tried to select `LDAC` through developer options seems no Bluetooth setting in there affect anything (nor bitrate nothing). But even if it did, there is no way to save selected profile, this option is temporary, for debugging purposes.
I am using loud expensive speakers with `dolby digital plus` audio card, and I would like to play from my phone wireless. `aptX HD` is not good enough, I clearly hear distortions. Its still "fine" though.

So, could i "hide" `blueZ` support of `aptX` codec for example? Or show it with a huge delay?

Ideal flow for devices with no LDAC support:
```
Connecting
Playing as SBC
Got the support of LDAC
Still playing as SBC
Got the support of aptX
Switching there as it preferable by Android ROM
```

Ideal flow for devices with LDAC support:
```
Connecting
Playing as SBC
Got the support of LDAC
Switching to LDAC there as it preferable by Android ROM
Got the support of aptX (or if it possible don't get data about it at all)
Still playing as LDAC cause they considered similar
```

I've read https://github.com/EHfive/pulseaudio-modules-bt/wiki#can-i-choose-codec-
But my OnePlus 5T with Android 8.1 has built-in LDAC support, and it still:

```
pactl list sources | grep -e bluez -e a2dp_codec
	Name: bluez_source.94_65_2D_C0_F5_5F.a2dp_source
	Driver: module-bluez5-device.c
		bluetooth.a2dp_codec = "APTX_HD"
		device.api = "bluez"
		bluez.path = "/org/bluez/hci0/dev_94_65_2D_C0_F5_5F"
		bluez.class = "0x5a020c"
		bluez.alias = "xxx"
```

**Comment by EHfive** [comment]
This module have no support of LDAC decoding. 

Simplified:
Encoding means sender.
Decoding means receiver.


You cannot send LDAC encoded audio to PA using this module.
