### ISSUE TITLE
[Question] How to change LDAC bit rate or force highest abrQualityModeID

### ISSUE THREAD

**Issue by rjshrjndrn** [EHfive/pulseaudio-modules-bt#136]
Hi,
First of all thanks for this awesome work.
One small question.
In wiki, I can see that LDAC [BitRate](https://github.com/EHfive/pulseaudio-modules-bt/wiki#ldac-bitrate-table)
My current device is Sony wh-1000mx4. And How can I check, on what bit rate audio is being streamed. And is there any way to force, `abrQualityModeID` to `0`

**Comment by EHfive** [comment]
https://github.com/EHfive/pulseaudio-modules-bt#configure

https://github.com/EHfive/pulseaudio-modules-bt#module-arguments

**Comment by ZLima12** [comment]
Useful links, thanks. Out of curiosity though, is there a way to check the current quality while it's set to the default?
