### ISSUE TITLE
[BUG] Can't build with libpulse/pulseaudio v13.99.3

### ISSUE THREAD

**Issue by zaeph** [EHfive/pulseaudio-modules-bt#138]
**Describe the bug**
The package doesn't build with libpulse/pulseaudio v13.99.3.  Downgrading libpulse/pulseaudio to v13.0 fixes the issue.  I didn't bisect to find the exact culprit.

**To Reproduce**
- Update libpulse/pulseaudio to v13.99.3.

**Environment (please complete the following information):**
 - Arch
 - libpulse/pulseaudio v13.99.3
 - [AUR package which fetches upstream](https://aur.archlinux.org/packages/pulseaudio-modules-bt-git/)

**Comment by asavah** [comment]
It does build fine with v13.99.3 here, it's not arch but pulse and pulse-audio-modules-bt are both build from sources.
You may want to raise this issue with you distros package maintainer.
And BTW `The package doesn't build` is not a bug report but a waste of time.
If it doesn't build there has to be an error message which you fail to provide.

**Comment by zaeph** [comment]
> And BTW The package doesn't build is not a bug report but a waste of time.

Apologies for wasting your time, then.
