### ISSUE TITLE
[BUG] Only SBC Available on WH-1000xm3

### ISSUE THREAD

**Issue by ibrokemypie** [EHfive/pulseaudio-modules-bt#142]
**Describe the bug**
Only SBC is listed as available in pactl, pavucontrol and hcidump. Setting to LDAC or aptX in pavucontrol returns ``pulseaudio[1780]: Refused to switch profile to a2dp_sink_ldac: Unavailable profile`` in the journal. The headphones used are Sony WH-1000xm3 which definitely have support of LDAC and aptX.

**To Reproduce**
Connect to WH-1000xm3 headphones via bluetooth, either via console or app.

**Expected behavior**
Multiple codecs are available, including aptX and LDAC

**Environment (please complete the following information):**
 - Distribution [e.g. Ubuntu, Fedora, Arch ...]
Arch

 - Pulseaudio Version [e.g. v12.2]
14.0-1

 - Version [e.g. v1.2]
r148.75af499-2

 - Installing via [e.g. manually compiled, precompiled package from xxx, ...]
Aur package "pulseaudio-modules-bt-git"

**Pulseaudio logs:**
https://0x0.st/i7Cd.log

**`avinfo` of device:**
```
$ avinfo CC:98:8B:80:7B:CC
Connecting ...
Stream End-Point #1: Audio Sink
	Media Codec: SBC
		Channel Modes: Mono DualChannel Stereo JointStereo
		Frequencies: 44.1Khz 48Khz
		Subbands: 4 8
		Blocks: 4 8 12 16
		Bitpool Range: 2-53
	Content Protection: SCMS-T
```

**Additional context**
According to the unofficial device compatibility table, aptX, aptX HD, aac and LDAC should all be supported
![image](https://user-images.githubusercontent.com/7827846/101233704-cab69d00-370d-11eb-8cc4-c9b19a9225cd.png)

**Comment by EHfive** [comment]
https://github.com/EHfive/pulseaudio-modules-bt/issues/111#issuecomment-629091180
> Switch to "High quality mode" in "Sony Headphones" IOS/Android app.
