### ISSUE TITLE
Get it into official repositories

### ISSUE THREAD

**Issue by raffaem** [EHfive/pulseaudio-modules-bt#145]
Given that libdac* is on the official repositories of Ubuntu, is it possible to get this module into the official repositories?

Where do I have to open the issue for this module to get into the official repositories?

Is [pulseaudio-module-bluetooth](https://packages.ubuntu.com/groovy/pulseaudio-module-bluetooth) the right one?

**Comment by EHfive** [comment]
No. And I am planning to deprecate this repo as long as PireWire is ready to go on bluetooth audio.

**Comment by EHfive** [comment]
Please don't use bug template if you are not going to report a bug.

**Comment by raffaem** [comment]
Why not? What is PireWire?

**Comment by EHfive** [comment]
Sry, it's PipeWire.
See #1 for why.
