### ISSUE TITLE
Dropping connection

### ISSUE THREAD

**Issue by orrpan** [EHfive/pulseaudio-modules-bt#30]
I lose connection spontaneously. I think the problem is coming from dbus

> [system] Rejected send message, 3 matched rules; type="method_return", sender=":1.25" (uid=112 pid=1724 comm="/usr/bin/pulseaudio --system --disallow-exit --dis") interface="(unset)" member="(unset)" error name="(unset)" requested_reply="0" destination=":1.3" (uid=0 pid=384 comm="/usr/lib/bluetooth/bluetoothd ")

Running 
` dpkg -l dbus`
Returns 
> dbus                                          1.10.26-0+deb9u1            armhf    

Any thoughts?

**Comment by EHfive** [comment]
I can't confirm it. (bluez 5.50, WH-1000XM2, A2DP codec: LDAC)

Please check if your bluez is broken first.

Please post the full context of system log.(from device not connected to connection losed)
