### ISSUE TITLE
bluetoothd[11111]: a2dp-sink profile connect failed for XX:XX:XX:XX:XX:XX: Protocol not available

### ISSUE THREAD

**Issue by okias** [EHfive/pulseaudio-modules-bt#33]
After pulseaudio-modules-bt instalation I getting this from EOZ Air bluetooth headphones.

pactl 12.2
Přeloženo s libpulse 12.2.0
Propojeno s libpulse 12.2.0

BlueZ: 5.50-r1 + some patches for a2dp codecs (without them it doesn't work either)
Linux: Gentoo ~amd64

Any ideas?
Thanks

**Comment by okias** [comment]
kinda looks like that bluez missing some patch, but no idea which one.

**Comment by EHfive** [comment]
Why not rebuild your bluez with those patches?

**Comment by EHfive** [comment]
Run `pactl list short modules | grep blue` to see if your bluetooth modules are loaded.

**Comment by okias** [comment]
no module loaded :(

**Comment by EHfive** [comment]
Append following lines to /etc/pulse/default.pa
```

.ifexists module-bluetooth-policy.so
load-module module-bluetooth-policy
.endif

.ifexists module-bluetooth-discover.so
load-module module-bluetooth-discover
.endif

```
And restart your pulseaudio, then check again.

**Comment by EHfive** [comment]
Any response?

**Comment by okias** [comment]
@EHfive cool, after running load module it's fine :) Thanks (I'll change config later)

**Comment by pacho2** [comment]
The problem is that, when building pulseaudio without its bluetooth support (as it collides with this one), that lines in default.pa config file are removed. Isn't there a way for pulseaudio-modules-bt to provide the proper config file on its side to prevent this?

Thanks!

**Comment by sriv** [comment]
I see something similar in popOS

```
bluetoothd[8257]: src/device.c:connect_profiles() /org/bluez/hci0/dev_XX_XX_XX_XX_XX_XX (all), client :1.175
bluetoothd[8257]: profiles/audio/a2dp.c:a2dp_sink_connect() path /org/bluez/hci0/dev_XX_XX_XX_XX_XX_XX
bluetoothd[8257]: a2dp-sink profile connect failed for XX:XX:XX:XX:XX:XX: Protocol not available
```

`/etc/pulse/default.pa` has the following entries:

```
### Automatically load driver modules for Bluetooth hardware
.ifexists module-bluetooth-policy.so
load-module module-bluetooth-policy
.endif

.ifexists module-bluetooth-discover.so
load-module module-bluetooth-discover
.endif
```
I tried to replace `load-module module-bluetooth-discover` with `load-module module-bluetooth-discover a2dp_config="ldac_eqmid=sq"` but it doesn't work.

The device I'm trying to pair is FiiO uBtr - https://www.fiio.com/%CE%BCbtr 

This device supports aptX (which I use in my android phone)

Please help!
