### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by comgang** [EHfive/pulseaudio-modules-bt#45]
I get the following error when I type make:
pulseaudio-modules-bt/src/modules/bluetooth/module-bluetooth-discover.c:52:9: error: too many arguments to function ‘pa_module_load’ pa_module_load(&mm, m->core, "module-bluez5-discover", m->argument);

**Comment by EHfive** [comment]
Duplicate #7 
Use pulseaudio>=11.59.1 

Why you gays don't read README?

**Comment by comgang** [comment]
I have Pulseaudio 12.2.
I've build it before without ffmpeg and everything worked fine.

**Comment by comgang** [comment]
Ok, I'm sorry. It seems I have installed Pulseaudio 12.2 but my libpulse-version is 10 (because it's debian stretch standard)
