### ISSUE TITLE
Is there a config option to force AAC codec?

### ISSUE THREAD

**Issue by uentity** [EHfive/pulseaudio-modules-bt#56]
I had an early preview of this module installed on Fedora 29 and noticed that my AKG-Y50BT was connecting using AAC codec instead of AptX as I expected.
After updating to Fedora 30 headphones begin constantly connecting via AptX codec. And surprisingly I found myself preferring AAC more.

Is there a config option to "force" AAC? I did changed `bluetooth.service` as WIKI describing, but don't see AAC in KDE profiles selection window.

**Comment by xstsx** [comment]
If you don't need AptX at all , you can compile without Aptx 
`cmake -DCODEC_APTX_HD_FF=OFF -DCODEC_APTX_FF=OFF`

**Comment by uentity** [comment]
Sound like Thanos Snap -)
Maybe there's another way?

**Comment by EHfive** [comment]
https://github.com/EHfive/pulseaudio-modules-bt/issues/53#issuecomment-484336536

In short, build latest version from pulseaudio-modules-bt git or bluez git yourself.

**Comment by uentity** [comment]
@EHfive build `pulseaudio-modules-bt` from current master, but situation didn't change.
Still, I only can use AptX and other codecs are listed as unavailable (including SBC). AAC profile not even listed in `pavucontrol`.

Is that because of outdated `bluez` in fedora?

**Comment by EHfive** [comment]
> In short, build ***latest*** version from pulseaudio-modules-bt git or bluez git yourself.

**Comment by gombosg** [comment]
Hi, now that `fdk-aac-free` is deemed to be GPL compatible I've made a Fedora build. Can you test [this build](http://koji.rpmfusion.org/koji/taskinfo?taskID=335570) with AAC? Thanks!
