### ISSUE TITLE
Please provide a way to disable native and ofono support at build time.

### ISSUE THREAD

**Issue by asavah** [EHfive/pulseaudio-modules-bt#58]
Feature request:
When building pulseaudio it's possible to disable "native" and "ofono" support via configure switches ```--disable-bluez5-ofono-headset --disable-bluez5-native-headset```, this allows to avoid the hassle with switching pa profiles and allow headsets to start in a2dp mode directly.

It would be nice to have such a knob when building this project, please consider it.
Thanks

**Comment by EHfive** [comment]
https://github.com/EHfive/pulseaudio-modules-bt/blob/65ffe335a419405ceef12742e72294e06d484491/config.h.in#L23-L24

Currently, you are able to disable "native" and "ofono" by deleting those lines in `config.h`.

But I would add cmake options making it configurable.

**Comment by asavah** [comment]
Yep, that's exactly what I did ))
But a cmake knob would be nice to have.

**Comment by EHfive** [comment]
Now you can disable both "native" and "ofono" by `cmake -DOFONO_HEADSET=OFF -DNATIVE_HEADSET=OFF <path to CMakeLists.txt's dir>`

**Comment by asavah** [comment]
Thank you!
