### ISSUE TITLE
All bluetooth  stereo headsets failed to connect

### ISSUE THREAD

**Issue by patricklibert** [EHfive/pulseaudio-modules-bt#62]
Ubuntu 18.04.2
Yesterday, 12 septermber 2019, i got an update through  the repository from EHfive.

Now all bluetooth stereo headsets failed to connect.
Also it doesn't work by the command bluetoothctl.
Message from bluetoothctl is: Failed to connect: org.bluez.Error.Failed

Thanks

**Comment by patricklibert** [comment]
Fixed, some broken packages in ubuntu...

**Comment by sbmw** [comment]
@patricklibert What was your solution here?

**Comment by patricklibert** [comment]
I don't know how exactly this happened but with an update my original ubuntu bluetooth packages where installed. I removed it and reinstalled the packages from this website.

**Comment by sbmw** [comment]
Ah OK, that's a different issue than I'm seeing, but thank you very much for the update.
