### ISSUE TITLE
Add support for battery level reporting

### ISSUE THREAD

**Issue by BlackSoulxxx** [EHfive/pulseaudio-modules-bt#66]
Can you add battery level reporting similar to Android and iOS? This may help you
https://github.com/sre/pulseaudio/commit/d66b66d20e9bc73e6d0ca89283cf2b5675304b00
In my case, Im using Audeze Cipher Bluetooth with aptX HD support. Tried bluetoothctl and found out it not using GATT.

**Comment by jaccc** [comment]
it would be useful

**Comment by berglh** [comment]
:+1:

**Comment by jtojnar** [comment]
Relevant https://gitlab.freedesktop.org/pulseaudio/pulseaudio/issues/722

**Comment by invidian** [comment]
I'm still interested in that feature.

**Comment by invidian** [comment]
Still :smile:

**Comment by userofryzen** [comment]
I am interested too, but.. may be it's not a problem of that modules(?)

**Comment by jaccc** [comment]
this script works for me when correct port is found
https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/blob/master/bl_battery.py

**Comment by bhack** [comment]
Please check https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/722#note_503760

**Comment by EHfive** [comment]
Close, I think it's not our business
