### ISSUE TITLE
Ubuntu installation issue

### ISSUE THREAD

**Issue by sbmw** [EHfive/pulseaudio-modules-bt#69]
Hi, I'm sorry if I'm missing something obvious, but the package installation isn't working for me on Ubuntu

I follow the basic package installation instructions

sudo add-apt-repository ppa:eh5/pulseaudio-a2dp
sudo apt-get update
sudo apt-get install libavcodec58 libldac pulseaudio-modules-bt

This process removes pulseaudio-module-bluetooth (and in turn module-bluetooth-discover) which then means I cannot connect my bluetooth headphones.  I get the following error in blueman "Connection Failed: blueman.bluez.errors.DBusFailedError: Protocol not available"

Ubuntu 18.04.2
pulseaudio 11.1
bluez 5.48
blueman 2.0.5

Many thanks

**Comment by EHfive** [comment]
Require pulseaudio >= 12.0

**Comment by EHfive** [comment]
U can simply run `apt upgrade` because eh5/pulseaudio-a2dp already inculdes pulseaudio 12.2 for Ubuntu 18.04.

**Comment by sbmw** [comment]
Ah, amazing!  Thanks!
