### ISSUE TITLE
Add FastStream patches for better microphone quality

### ISSUE THREAD

**Issue by ni-ka** [EHfive/pulseaudio-modules-bt#76]
AFAIK this is currently the only way to avoid using HSP / HFP codec for calls:
https://lists.freedesktop.org/archives/pulseaudio-discuss/2019-June/031175.html

**Comment by soredake** [comment]
Any progress on this?

**Comment by bhack** [comment]
Check https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/227
