### ISSUE TITLE
how to use aptx?

### ISSUE THREAD

**Issue by digitxo** [EHfive/pulseaudio-modules-bt#81]
I just installed this module and I have some questions.

How do I actually play a stream with the aptx codecs?

example:

arecorder | aplay

but with pulse and aptx...
if it takes some programming, clue me in!

**Comment by EHfive** [comment]
This module is just a caller of FFmpeg.
Use FFmpeg 4.0+ or https://github.com/pali/libopenaptx if you need to decode/encode aptx directly.
