### ISSUE TITLE
didn't work with pulseaudio 13.0 on Gentoo

### ISSUE THREAD

**Issue by YangMame** [EHfive/pulseaudio-modules-bt#83]
System: gentoo with unstable 
```
mame@Laptop ~ $ pulseaudio --version
pulseaudio 13.0
mame@Laptop ~ $ tail -f /etc/pulse/default.pa 

# Bluetooth
.ifexists module-bluetooth-policy.so
load-module module-bluetooth-policy
.endif

.ifexists module-bluetooth-discover.so
load-module module-bluetooth-discover
.endif

mame@Laptop ~ $ LANG="en_US" pulseaudio --start
E: [pulseaudio] main.c: Daemon startup failed.
```

**Comment by EHfive** [comment]
https://github.com/EHfive/pulseaudio-modules-bt/issues/80#issuecomment-537955189
> the pulseaudio-modules-bt ebuild in gentoo simply is missing a step to update the pa-submodule to the right version, so it's always compiled against pulseaudio v12.2 (which is checked out by default), that's why it segfaults

Need someone to issue a bug on https://packages.gentoo.org/packages/media-sound/pulseaudio-modules-bt.

**Comment by Jjeje007** [comment]
Bug report opened : [https://bugs.gentoo.org/696912](url)

**Comment by EHfive** [comment]
Current workaround:

This way you can force checkout pulseaudio v13.0
```
# export EGIT_OVERRIDE_COMMIT_PULSEAUDIO_PULSEAUDIO=v13.0
# USE="dbus" emerge media-sound/pulseaudio media-sound/pulseaudio-modules-bt 
```

Pulseaudio v13 ebuild disable `dbus` if `bluetooth` is unused but `pulseaudio-modules-bt` still requires it, therefore you need to append `dbus` USE flag to `media-sound/pulseaudio`

**Comment by EHfive** [comment]
https://github.com/EHfive/pulseaudio-modules-bt/issues/83#issuecomment-539131879
> Bug report opened : https://bugs.gentoo.org/696912

https://github.com/EHfive/pulseaudio-modules-bt/issues/83#issuecomment-539173067
> Current workaround:
> ........

@pacho2 I thought you could help on the essay.

**Comment by pacho2** [comment]
It works fine

Thanks a lot for your help!

**Comment by EHfive** [comment]
https://bugs.gentoo.org/696912#c4

Close.
