### ISSUE TITLE
Core dump with pulseaudio 13

### ISSUE THREAD

**Issue by vrossum** [EHfive/pulseaudio-modules-bt#86]
After upgrad from 19.04 to Ubuntu 19.10 (pulseaudio 13), recompilation of the drivers, pulseaudio core dumps.

See attached log.
Reverting to stock install of pulseaudio fixes it.
It is probably related to the other bugs reported herefor Gentoo

[bt_19-10.txt](https://github.com/EHfive/pulseaudio-modules-bt/files/3744930/bt_19-10.txt)

**Comment by EHfive** [comment]
Duplicate #85, Ubuntu 19.10 not support yet
