### ISSUE TITLE
Can not switch audio profiles

### ISSUE THREAD

**Issue by rhalina** [EHfive/pulseaudio-modules-bt#88]
Hi, 

I'm running  pulseaudio 13.0 and bluez 5.50 on debian testing and just did a completely fresh rebuild of the current pulseaudio-modules-bt git which worked fine without any errors. 
All the modules are freshly build and present at /usr/lib/pulse-13.0/modules. I restarted pulseaudio and bluetooth.

pavucontrol and pactl set-card-profile show me all the expected a2dp_sink profiles (a2dp_sink_aac, a2dp_sink_aptx, a2dp_sink_aptx_hd, a2dp_sink_sbc, headset_head_unit, off), but I cannot change to any a2dp_sink profile. 

`pactl set-card-profile bluez_card.CC_98_8B_57_43_28 a2dp_sink_aptx 
Failure: Input/Output error
`
No logfiles I could find reveal any additional information on this. 

Note: All this did work in the past with the same machine and the same headphones, but I think it was under pulseaudio 12.2

Maybe I'm missing something here. Does somebody have a pointer? 

Thanks alot
rhalina

**Comment by EHfive** [comment]
https://github.com/EHfive/pulseaudio-modules-bt/wiki#can-i-choose-codec-

Install bluez >= 5.51 and then enable its experimental interfaces.
