### ISSUE TITLE
Excellent job: thanks for creating :)

### ISSUE THREAD

**Issue by mannp** [EHfive/pulseaudio-modules-bt#98]
Running nicely on arch linux!

**Comment by EHfive** [comment]
Thanks.

You don't need to open an issue, just star it.

**Comment by lkraav** [comment]
I've seen new Discussion module in a few projects I'm following. Maybe people do want to chat here as well.

**Comment by mannp** [comment]
> Thanks.
> 
> You don't need to fire an issue, just star it.

Sure, thought it deserved more that a star, but feel free to delete the issue if its crud.
